modLoader="javafml"
loaderVersion="[${forge_loader_major},)"
license="MIT"
[[mods]]
modId="orbital_railgun_enhanced"
version="${version}"
displayName="Orbital Railgun Enhanced"
authors="Mishkis, KingIronMan2011"
logoFile="assets/orbital_railgun_enhanced/icon.png"
description="Orbital Railgun with enhanced sounds, effects and controls for Minecraft 26.3."
[[mixins]]
config="orbital_railgun_enhanced.mixins.json"
[[dependencies.orbital_railgun_enhanced]]
modId="minecraft"
mandatory=true
versionRange="[26.3]"
ordering="NONE"
side="BOTH"
[[dependencies.orbital_railgun_enhanced]]
modId="forge"
mandatory=true
versionRange="[${forge_api_version},)"
ordering="NONE"
side="BOTH"
