org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4
minecraft_version=26.3
mod_version=2.1.0+26.3
maven_group=io.github.kingironman2011
fabric_loader_version=0.19.5
fabric_api_version=0.160.7+26.3
neo_version=26.3.0.4-beta
forge_version=
net.minecraftforge.gradle.merge-source-sets=true

quilt_loader_version=0.31.0-beta.4
