modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="orbital_railgun_enhanced"
version="${version}"
displayName="Orbital Railgun Enhanced"
authors="Mishkis, KingIronMan2011"
iconFile="assets/orbital_railgun_enhanced/icon.png"
description="Orbital Railgun with enhanced sounds, effects and controls for Minecraft 26.3."
[[mixins]]
config="orbital_railgun_enhanced.mixins.json"
[[dependencies.orbital_railgun_enhanced]]
modId="minecraft"
type="required"
versionRange="[26.3]"
ordering="NONE"
side="BOTH"
[[dependencies.orbital_railgun_enhanced]]
modId="neoforge"
type="required"
versionRange="[26.3.0.4-beta,)"
ordering="NONE"
side="BOTH"
